# Generated by Django 2.2.2 on 2019-06-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='number',
            field=models.IntegerField(help_text='enter number of choice'),
        ),
    ]
