# Generated by Django 2.2.2 on 2019-06-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_remove_discipline_disciplines'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='right_choice',
            field=models.IntegerField(default=1),
        ),
    ]
