# Generated by Django 2.2.2 on 2019-06-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_choice_right_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='right_choice',
        ),
        migrations.AddField(
            model_name='question',
            name='right_choice',
            field=models.IntegerField(default=1),
        ),
    ]
