# Generated by Django 2.2.2 on 2019-06-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20190607_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
