# Generated by Django 2.2.2 on 2019-06-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_test_bal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='bal',
            field=models.FloatField(default=0),
        ),
    ]
