# Generated by Django 2.2.2 on 2019-06-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20190609_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='bal',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='count',
            field=models.FloatField(),
        ),
    ]
