# Generated by Django 2.2.2 on 2019-06-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_remove_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
